source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASCalendar_Example', :exclusive => true do
  pod "ASCalendar", :path => "../"
end

target 'ASCalendar_Tests', :exclusive => true do
  pod "ASCalendar", :path => "../"

  
end
